### ISSUE TITLE
Remove Duplicate Data Captured by Multiple Agents

### ISSUE THREAD

**Issue by BrysonMcI** [BrysonMcI/Open-Network-Nodeifier#29]

**Comment by ohanf** [comment]
This is interesting, how do we deploy agents? To every endpoint/node/workstation? Just a couple agents on core switches? Also how do we capture traffic? I assume non-promiscuous mode, but ingress+egress, or do we only pick one?

**Comment by BrysonMcI** [comment]
However you want, should allow for deployment on a few promiscuous hosts,
or many agents across many endpoints (promiscuous would be fine here).
Deployment would just be a pull of the agent code, install python, install
pyshark, run with server ip as cmd arg.

On Oct 16, 2017 15:11, "ohfill" <notifications@github.com> wrote:

This is interesting, how do we deploy agents? To every
endpoint/node/workstation? Just a couple agents on core switches? Also how
do we capture traffic? I assume non-promiscuous mode, but ingress+egress,
or do we only pick one?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BrysonMcI/Open-Network-Nodeifier/issues/29#issuecomment-337001230>,
or mute the thread
